// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS1lFFsePBBT-4lmgi3tZvSPEbT1FyJYg',
    appId: '1:916015799071:web:53db8964fe9d25e9b8ae2a',
    messagingSenderId: '916015799071',
    projectId: 'home-bite-e867e',
    authDomain: 'home-bite-e867e.firebaseapp.com',
    storageBucket: 'home-bite-e867e.firebasestorage.app',
    measurementId: 'G-RB06DGQ2K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_TykNRpfSLBtMwkZWuYnP7AisWcOr9E',
    appId: '1:916015799071:android:8b048bbf6d5aae67b8ae2a',
    messagingSenderId: '916015799071',
    projectId: 'home-bite-e867e',
    storageBucket: 'home-bite-e867e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9heePUOs2oltvjcidknau8KdRNdGlNdM',
    appId: '1:916015799071:ios:2552d494ab22369fb8ae2a',
    messagingSenderId: '916015799071',
    projectId: 'home-bite-e867e',
    storageBucket: 'home-bite-e867e.firebasestorage.app',
    iosBundleId: 'com.example.homeBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9heePUOs2oltvjcidknau8KdRNdGlNdM',
    appId: '1:916015799071:ios:2552d494ab22369fb8ae2a',
    messagingSenderId: '916015799071',
    projectId: 'home-bite-e867e',
    storageBucket: 'home-bite-e867e.firebasestorage.app',
    iosBundleId: 'com.example.homeBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS1lFFsePBBT-4lmgi3tZvSPEbT1FyJYg',
    appId: '1:916015799071:web:8519855d0ced6a71b8ae2a',
    messagingSenderId: '916015799071',
    projectId: 'home-bite-e867e',
    authDomain: 'home-bite-e867e.firebaseapp.com',
    storageBucket: 'home-bite-e867e.firebasestorage.app',
    measurementId: 'G-KBG38K178G',
  );

}